### ISSUE TITLE
Please add an error handler

### ISSUE THREAD

**Issue by bermudashawn** [eloquence/freeyourstuff.cc#122]
Since the advent of Spaces in Quora, I have not been able to download my content. I have traced it back to an error in the URL provided by Quora to the comment: 

> Error: Value "https://www.quora.comhttps://www.quora.com/q/fslgdpvzrtvxossm/Are-secrets-revealed-during-the-afterlife" should be a qualified web or FTP URL, but is not.

I have asked Quora to fix this, but it would be much more user friendly if you added an error handler except crashing after downloading 95% of the content.

Thank you.

<img width="441" alt="Screen Shot 2019-11-12 at 10 34 06 PM" src="https://user-images.githubusercontent.com/55843132/68858325-2d7c6700-06bb-11ea-8b41-72ccb094c8ad.png">

**Comment by eloquence** [comment]
Hi Shawn, thanks for the additional info -- this error was indeed due to a difference in how Quora outputs URL on "Spaces" pages. This should now be fixed in version 0.5.5 of the extension -- check chrome://extensions/ in your browser to see which version you're on, and give it a few hours if it's not updated yet (it should auto-update).

You have a lot of answers, and you might still encounter other issues with the download -- please let me know if you run into this issue again, or anything else. Thanks!

**Comment by bermudashawn** [comment]
When I updated the extension to 0.5.5 Chrome gives me this error using Mac Version 78.0.3904.97 (Official Build) (64-bit)

<img width="411" alt="Screen Shot 2019-11-18 at 8 18 00 AM" src="https://user-images.githubusercontent.com/55843132/69052026-54e57380-09dc-11ea-9aa5-7dfb37065498.png">
<img width="650" alt="Screen Shot 2019-11-18 at 8 17 40 AM" src="https://user-images.githubusercontent.com/55843132/69052040-57e06400-09dc-11ea-9a23-8bc29d05c2a0.png">

**Comment by eloquence** [comment]
Hi Shawn, sorry for the late response, I missed this comment when you wrote it. It is possible that you attempted to download a CRX file and opened it manually? I recommend removing and reinstalling the extension by using the "Add to Chrome" button on this page:

https://chrome.google.com/webstore/detail/free-your-stuff/hlkhpekhgcaigleojiocoeockhcaglia

If you want to install it from source, note that the Chrome Store adds content to the archive that conflicts with the "Load unpacked" feature in developer mode. So the recommended method for installing the extension from source is to clone this git repository, then "load unpacked" the extension directory.

BTW, I _just_ fixed another issue with "Spaces" that caused the `moment` error you were seeing. Basically, "Spaces" add a byline after the date which broke the date-parsing for those answers. This should be fixed in 0.5.6.
