### ISSUE TITLE
Downloading 0 of null. 

### ISSUE THREAD

**Issue by bermudashawn** [eloquence/freeyourstuff.cc#136]
The plug-in stopped working and I have seen no change after reformatting my HD and doing a clean install of everything. 

<img width="423" alt="Screen Shot 2020-04-20 at 9 16 27 PM" src="https://user-images.githubusercontent.com/55843132/79790631-54b32080-834c-11ea-96ca-56228bca917c.png">

**Comment by eloquence** [comment]
Yeah I saw this yesterday. Unfortunately Quora made major CSS changes which broke everything. :/ To make matters worse their output is now even more unparseable than before. This will take some time to sort out, sorry for the inconvenience.

**Comment by bermudashawn** [comment]
Any update on the extension?

The plug-in asks me to log in, but I already am. Any ideas?

**Comment by eloquence** [comment]
Sorry, it's still broken for Quora right now. :( The recent Quora layout changes (under the hood) are pretty extensive. It's fixable but will likely be very brittle because it's difficult to target specific elements like "the subject or the answer" or the "contents of the answer" reliably in the new HTML, due to the same CSS class names being used all over the place. I'll take a stab at a first fix as soon as I'm able. 

The best long term strategy I can think of is to switch to exporting answers one-by-one from the "Your Content" page. That may be slower, but would likely also be more reliable for large answer sets. Unfortunately, that page is not visible for any account other than your own, and I only have a few answers on my account, so it's difficult for me to test by myself. But if you or others have time to help (we might have to schedule a screen-sharing session), I can take a stab at it.

**Comment by eloquence** [comment]
(See #137 for latest update, closing as duplicate)
