### ISSUE TITLE
Quora download timeout, deduplicating repeat downloaded items

### ISSUE THREAD

**Issue by opoudjis** [eloquence/freeyourstuff.cc#70]
Yes, Quora.

I'm sorry.

I have had multiple freezes and timeouts as well in my attempt to free my content. My download has just finished, and while it has the correct answer count (2500), it seems to have redownloaded multiple instances of the latest few answers, with the consequence that it is missing my first few months. It would appear that when download is reattempted, it starts from the top answer, but does not deduplicate newly downloaded answers.

I'm happy to try writing the other two plugins needed, btw, but waiting for this to clear up first. :)

User name opoudjis at gmail . com, in case you want to inspect my content. https://freeyourstuff.cc/user/59479309d6f0e41553282ea9

**Comment by eloquence** [comment]
Hi Nick,

Thanks for giving it a spin. I just rewrote the Quora plugin a bit to handle the frequent UI changes on Quora's end a bit better. I tested it on your account and it just chokes and dies - debugging a bit, it seems to just run out of memory when all ~2500 answers are expanded. I think the best solution would be to change the way we're extracting answers, perhaps only for accounts with lots of them -- instead of trying to expand them all in place, we can open one separate web request for each answer. That may slow down the download a fair bit, but should be more reliable for large jobs.

I'll take a crack at this and will let you know how it goes.

**Comment by eloquence** [comment]
Okay, the "one request per answer" approach works better in theory, but in practice, Quora throws a "too many requests" error after a while and refuses any connection from your IP. For how long, I don't know yet. Probably the only way to avoid that with lots of answers is to either support ranges (answers 1-100 etc.), or to automatically take a break when this happens. Will poke a bit more.

**Comment by opoudjis** [comment]
They're evil, aren't they.

Maybe have a look at https://github.com/t3nsor/quora-backup ? I haven't had timeouts in using it, and I have downloaded 1000 answers in one go with it; the interval between downloads seems to be one or two sec. Of course, that solution won't necessarily be transferrable from Python to JS...

**Comment by eloquence** [comment]
I'm now doing a sequential in-line expansion of the comments, which scales better to large answer sets (but takes a bit longer). I was able to donwnload your answer set in 30 minutes or so. Let me know if you'd like me to send you a copy; if you'd like to try yourself, just make sure you're running version 0.3.19 of the extension.

**Comment by eloquence** [comment]
Closing this for now since folks seem to be able to download fairly large answer sets since the rewrite. Feel free to reopen if you still encounter issues.
